---
- name: 'Delete UCI list item {{ _uci_prefix_key ~ _uci_item.key }}'  # noqa: ignore-errors
  ansible.builtin.shell:
    cmd: |
      uci delete {{ _uci_prefix_key ~ _uci_item.key }}
  changed_when: true
  ignore_errors: true
  become: true
  notify: 'Commit uci changes'

- name: >-
    Create/update {{ _uci_item.key }} UCI key with value {{ __tmp_uci_value }} (prefix:
    {{ _uci_prefix_key }}) (idempotency) (list)'  # noqa: name  # nospell
  ansible.builtin.shell:
    cmd: |
      uci add_list {{ _uci_prefix_key ~ _uci_item.key }}={{ _uci_list_item }}
  changed_when: true
  loop: '{{ __tmp_uci_value }}'
  loop_control:
    loop_var: '_uci_list_item'
  notify: 'Commit uci changes'
  become: true
...
