---
role_name_check: 1

driver:
  name: 'podman'

platforms:
  - name: '21.02'
    image: 'docker.io/openwrtorg/rootfs:x86-generic-openwrt-21.02'
    command: '/sbin/init'
    capabilities:
      - 'SYS_ADMIN'
    pre_build_image: true
    privileged: true

  - name: '22.03'
    image: 'docker.io/openwrtorg/rootfs:x86-generic-openwrt-22.03'
    command: '/sbin/init'
    capabilities:
      - 'SYS_ADMIN'
    pre_build_image: true
    privileged: true

  - name: 'snapshot'
    image: 'docker.io/openwrtorg/rootfs:x86-generic-snapshot'
    command: '/sbin/init'
    capabilities:
      - 'SYS_ADMIN'
    pre_build_image: true
    privileged: true

provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callbacks_enabled: 'profile_tasks, timer'
      remote_user: 'root'
    ssh_connection:
      pipelining: false

dependency:
  name: 'galaxy'
  options:
    requirements-file: 'collections/requirements.yml'

verifier:
  name: 'ansible'

scenario:
  test_sequence:
    - 'dependency'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'idempotence'
    - 'verify'
    - 'destroy'
