---
- name: 'Prepare OpenWrt instance to test playbook'
  hosts: 'all'
  become: true
  gather_facts: false
  vars:
    _required_packages:
      - 'python3'

  tasks:
    - name: 'Wait for OpenWrt container to come up properly'
      ansible.builtin.pause:
        seconds: 30

    - name: 'Ensure resolv.conf contains Google DNS'
      ansible.builtin.raw: >
        /bin/echo 'nameserver 8.8.8.8' > /etc/resolv.conf
      args:
        executable: '/bin/ash'
      changed_when: true

    - name: 'Ensure opkg cache is up to date'  # noqa: ignore-errors
      ansible.builtin.raw: '/bin/opkg update'
      args:
        executable: '/bin/ash'
      changed_when: false
      ignore_errors: true

    - name: 'Ensure minimal required packages are installed for Ansible to work'
      ansible.builtin.raw: >
        /bin/opkg install {{ _required_packages | join(' ') }}
      args:
        executable: '/bin/ash'
      register: '__t_opkg_install'
      changed_when: "__t_opkg_install.stdout_lines | reject('match', '^.+is up to date.$') | length > 0"
...
