name: Molecule

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  molecule:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - 'default'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          path: '${{ github.repository }}'

      - name: 'Molecule'
        uses: 'gofrolist/molecule-action@v2'
        with:
          molecule_command: 'test'
          molecule_args: '--scenario-name ${{ matrix.scenario }} --driver-name podman'
          molecule_working_dir: '${{ github.repository }}'
          molecule_options: '--debug -v'
